### PR TITLE
Build fixes and logging of encoded frames

### PR DESCRIPTION
**Pull request by uniemimu**
Ref:

https://github.com/intel/gstreamer-media-SDK/issues/149 (although fix is limited to gstreamer-**1.0** just like cmake is)
https://github.com/intel/gstreamer-media-SDK/issues/148
https://github.com/intel/gstreamer-media-SDK/issues/146

### CODE REVIEW

**Comment by ishmael1985** [comment]
@siewhoon perhaps if this passes the tests this could be merged?

**Comment by SiewHoon** [comment]
I will rejected this pull request.
I will merge in "meson.build: set install_dir" patch.

**Comment by SiewHoon** [comment]
I didn't against Gstreamer plugin or MSDK library. I can't straight accept this solution and go broken the existing software support already shipped out. That patch didn't come out with a proper right solution.

Now I already fixed it. I will merge it after done code review.  

Here is the code fixed and verify it: 
[0001-meson-build-fixed-find-mfx-dependecy-with-and-withou.patch.txt](https://github.com/intel/gstreamer-media-SDK/files/3165369/0001-meson-build-fixed-find-mfx-dependecy-with-and-withou.patch.txt)

**Comment by eero-t** [comment]
Yes, fallback to MFX_HOME in case MSDK isn't otherwise found is better.

**Pull request closed without merging**
