### PR TITLE
HEVC 10-bit decode support for Apollo Lake platforms running Linux, new mfxvpp options and a bunch of important fixes

### PR DESCRIPTION
**Pull request by ishmael1985**

### CODE REVIEW

**Comment by SiewHoon** [comment]
Go check again for this video - gst-play-1.0 bianxingjinggang.mp4
Before this 74 code changed, the video has slightly stuttered. 
But with new pull code in, the video playback become worse.

**Comment by ishmael1985** [comment]
This branch has not yet dealt with issue #41. Clips like aichong.mp4, ailisi.mp4 and bianxingjinggang.mp4, the playback is pretty bad. I got this for bianxingjinggang.mp4:

image

I believe the rest should be ok.

**Comment by SiewHoon** [comment]
Then I will suggest you submit the new issue to track in for topic branch.

**Comment by ishmael1985** [comment]
Sure. I still need to investigate exactly the cause why these clips do badly with gst-play-1.0, but with gst-launch-1.0, the decode is fine for those 3 clips.

**Comment by ishmael1985** [comment]
Hmm... it works perfectly on GStreamer version 1.13.1 for me with X11 DRI3 rendering, all 3 clips.

image

**Comment by ishmael1985** [comment]
Commit 17ecf64 is quite important as it resolves an important issue for gl interop. Prior to this, rendering issues can be seen through the following simple pipeline:

GST_GL_PLATFORM=egl gst-launch-1.0 filesrc location=/path/to/video.mp4 ! qtdemux ! h264parse ! mfxdecode ! video/x-raw, format=NV12 ! glimagesink

**Pull request merged**
